name: Math Operations Action
description: Generates sum and multiplication of two input numbers

inputs:
  number-1:
    description: First number
    required: true
    default: "0"
  number-2:
    description: Second number
    required: true
    default: "0"

outputs:
  sum:
    description: Sum of the two numbers
    value: ${{ steps.sum.outputs.result }}
  multiplication:
    description: Multiplication of the two numbers
    value: ${{ steps.multiplication.outputs.result }}
  subtraction:
    description: Subtraction of the two numbers
    value: ${{ steps.subtraction.outputs.result }}
  division:
    description: Division of the two numbers
    value: ${{ steps.division.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: sum
      run: echo "sum=$(echo $((${{ inputs.number-1 }} + ${{ inputs.number-2 }})))" >> $GITHUB_OUTPUT
      shell: bash
    # - id: sum
    #   run: echo "::set-output name=result::$((${{ inputs.number-1 }} + ${{ inputs.number-2 }}))"
    #   shell: bash
    # - id: subtraction
    #   run: echo "::set-output name=result::$((${{ inputs.number-1 }} - ${{ inputs.number-2 }}))"
    #   shell: bash
    # - id: division
    #   run: echo "::set-output name=result::$((${{ inputs.number-1 }} / ${{ inputs.number-2 }}))"
    #   shell: bash
#  run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
