name: "Hello Github User"
author: "Bigismall"
description: "Just a sample composite action"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number output:"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - id: print-hello
      run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - id: print-action-path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: run-goodbye-shell-script
      run: goodbye.sh
      shell: bash
