name: Composite Action Math
on: 
    workflow_dispatch:
        inputs:
            number-1:
                description: First number
                required: true
                default: "0"
            number-2:
                description: Second number
                required: true
                default: "0"

jobs:
  math-operations:
    runs-on: ubuntu-latest
    name: Math operations
    steps:
      - uses: actions/checkout@v4
      - id: call-math-operations-action
        uses: ./.github/actions/math-operations-action
        with:
          number-1: ${{ inputs.number-1 }}
          number-2: ${{ inputs.number-2 }}
    #   - run: echo "(+) ${{ steps.call-math-operations-action.outputs.output-sum }}"
    #     shell: bash 
    #   - run: echo "(-) ${{ steps.call-math-operations-action.outputs.output-subtraction }}"
    #     shell: bash 
    #   - run: echo "(*) ${{ steps.call-math-operations-action.outputs.output-multiplication }}"
    #     shell: bash 
    #   - run: echo "(/) ${{ steps.call-math-operations-action.outputs.output-division }}"
    #     shell: bash        
      - run: echo "All outputs ${{ toJson(steps.call-math-operations-action.outputs) }}"
        shell: bash
                

# ${{ steps.call-hello-user-action.outputs.random-number }}
#         steps:
#   - uses: actions/checkout@v4
#   - id: call-math-operations-action
#     uses: ./.github/actions/math-operations-action
#     with:
#       number-1: ${{ inputs.number-1 }}
#       number-2: ${{ inputs.number-2 }}
#   - name: Display results
#     run: echo "(${{ matrix.operation }}) ${{ steps.call-math-operations-action.outputs[matrix.operation] }}"
#     shell: bash
#     strategy:
#       matrix:
#         operation: ['sum', 'subtraction', 'multiplication', 'division']