name: Composite Action test
on: 
    workflow_dispatch:
     inputs:
      input-name:
        description: 'Say Hello to:'
        required: true
        default: ''
        type: string

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello and generate a random number
    steps:
      - uses: actions/checkout@v4
      - id: call-hello-user-action
        uses: ./.github/actions/hello-user-action
        with:
          who-to-greet: ${{ inputs.input-name }}
      - run: echo random-number ${{ steps.call-hello-user-action.outputs.random-number }}
        shell: bash        
