name: First workflow
on: push
jobs:
    job1:
        name: First job 
        runs-on: ubuntu-latest
        steps:
            - name: First step
              run: echo "Hello ${{GITHUB_REPOSITORY_OWNER}}"
            - name: Second step
              run: env | sort


