name: First workflow
on:
    push:
        branches:
            - hemp
jobs:
    job1:
        name: First job 
        runs-on: ubuntu-latest
        steps:
            - name: First step
              run: echo "Hello owner ${{github.repository_owner}}"
    job2:
        name: Second job
        runs-on: ubuntu-latest
        steps:
            - name: Second step
              run: echo "Hello repo url ${{github.repositoryUrl}}"
    job3:
        name: Third job
        runs-on: ubuntu-latest
        needs: [job1, job2]
        steps:
            - name: Third step
              run: echo "Both jobs completed"
            
