name: Javascript Action test
on:
    workflow_dispatch:
        inputs:
            who-to-greet:
                description: 'Who to greet'
                required: true
                default: 'Mona the Octocat'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
        id: checkout-first-javascript-action  
      - name: Hello Mona action step
        id: hello
        uses: ./.github/actions/first-javascript-action
        with:
          who-to-greet:  ${{ inputs.who-to-greet}}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
