name: Draw a smile
run-name: ${{ github.actor }} is drawing Smile with SIPS
env:
    SMILE_FILE: smile.png
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Show smile to:'
        required: true
        default: ''
        type: string
jobs:
    draw:
        runs-on: macos-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.1

          - name: Draw
            run: sips -j ./smile/smile.js -o ./smile/${{env.SMILE_FILE}}

          - name: Upload
            uses: actions/upload-artifact@v3
            with:
                name: ${{env.SMILE_FILE}}
                path: ./smile/${{env.SMILE_FILE}}
                retention-days: 3
    


        