name: TypeScript action test
on:
    workflow_dispatch:
        inputs:
            seconds:
                description: 'Seconds to wait'
                required: true
                default: '5'
jobs:
    test-ts-action:
        runs-on: ubuntu-latest
        steps:
            - name: Run first TypeScript action
              id: test-action
              uses: Bigismall/typescript-github-action@v1.0.0.0-alpha
              with:
                  seconds: ${{ github.event.inputs.seconds }}
            - name: Print Output
              id: output
              run: echo "The time is now ${{steps.test-action.outputs.time}}, so You had to wait ${{ inputs.seconds }} seconds"